"""Task-specific native props, visual themes and English instructional steps."""
PROFILES={
'q01':('room',['LiquidPumpingStation','WashBasin','Outhouse'],'Plan an exit|Supply dirt to the outhouse|Supply clean water to the basin|Enclose the latrine|Observe toilet use followed by washing'),
'q01_dining':('research_room',['ResearchCenter','DiningTable'],'Prepare a research station|Research Meal Preparation|Construct mess tables|Enclose the dining room|Verify the mess hall'),
'q02':('tools',['Bed','ManualGenerator','MineralDeoxidizer'],'Inspect room, power and oxygen overlays|Adjust schedules|Check work permissions|Set construction priorities'),
'q03':('oxygen',['ManualGenerator','Battery','MineralDeoxidizer'],'Construct an oxygen diffuser|Connect power|Supply algae|Inspect pressure and oxygen distribution|Keep a route for gas circulation'),
'c2_water':('water',['LiquidPumpingStation','LiquidPump','WaterPurifier'],'Identify the liquid|Preserve the reservoir boundary|Build reachable water access|Plan replenishment or purification'),
'q06':('farm',['PlanterBox','FarmTile'],'Read plant information|Select a crop|Choose a suitable site|Build planting facilities|Supply the resources required by the plant'),
'c2_food_budget':('budget',['PlanterBox','RationBox','MicrobeMusher'],'Count edible calories|Compare production and consumption|Buffer the harvest interval|Adjust crops or recipes'),
'q08':('farm',['FarmTile','HydroponicFarm'],'Check food crops and thimble reed separately|Prepare the planting area|Connect irrigation|Observe the first growth cycle'),
'q12':('storage',['RationBox','Refrigerator','StorageLocker'],'Distinguish germs from food spoilage|Plan food storage|Reduce contaminated deliveries|Check temperature and storage atmosphere'),
'q20':('farm',['HydroponicFarm','CeilingLight','CookingStation'],'Read crop requirements|Check the water budget|Prepare lighting and planting|Observe a harvest|Choose food processing'),
'c3_power':('power',['ManualGenerator','Battery','MineralDeoxidizer'],'Generate power|Connect wires|Connect essential consumers|Inspect the power overlay|Compare load with wire capacity'),
'q04':('research',['ResearchCenter','AdvancedResearchCenter'],'Choose the target building|Read its technology prerequisites|Build the required research stations|Supply research materials|Inspect each utility overlay separately'),
'q07':('power',['ManualGenerator','PowerTransformer','MineralDeoxidizer'],'Count the circuit load|Separate consumer branches|Connect transformer input and output|Inspect the power overlay|Test the circuit'),
'c3_pipes':('pipes',['LiquidPump','LiquidReservoir','GasPump'],'Identify source and destination|Connect output to input|Check bridge direction|Start a trial|Observe blockages'),
'c3_waste':('waste',['FlushToilet','LiquidReservoir','WaterPurifier'],'Count waste sources|Collect different wastes separately|Plan storage or treatment|Check treatment product destinations'),
'q05':('waste',['FlushToilet','WaterPurifier','LiquidReservoir'],'Connect toilet water input|Connect polluted water output|Prepare water treatment|Supply initial water|Provide an outlet for excess liquid'),
'q14':('explore',['Tile','Ladder','LiquidPumpingStation'],'Pause and inspect gas and temperature|Mark reservoirs and dangerous areas|Dig in sections|Keep barriers and access routes'),
'c4_biomes':('explore',['Ladder','SuitLocker','SuitMarker'],'Inspect temperature, gas and germs|Establish a safe entrance|Explore a small area|Bring back the required resources'),
'c4_temperature':('heat',['InsulationTile','LiquidConditioner','SteamTurbine'],'Locate heat sources|Isolate the living area|Design a heat transfer loop|Choose the final heat sink|Observe temperature changes'),
'q22':('nature',['ParkSign','InsulationTile'],'Preserve natural plants|Plan the commute route|Verify the nature reserve in the overlay|Isolate production heat'),
'q11':('heat',['MetalRefinery','LiquidReservoir','SteamTurbine'],'Check the recipe|Connect inputs and outputs|Prepare a coolant loop|Produce a small batch|Inspect coolant temperature'),
'q15':('research',['ResearchCenter','AdvancedResearchCenter','NuclearResearchCenter'],'Choose the needed building first|Read its technology chain|Prepare the required research stations|Assign a researcher|Research one prerequisite at a time'),
'c5_resources':('budget',['LiquidReservoir','GasReservoir','RationBox'],'List water, oxygen, food, fuel and materials|Measure consumption|Choose replenishable sources|Set buffers and maintenance'),
'c5_automation':('automation',['BatterySmart','switchpower_kanim','ManualGenerator'],'Define the start and stop conditions|Choose a sensor|Connect automation signals|Set the threshold|Test both signal states'),
'q09':('oxygen',['LiquidPump','Electrolyzer','GasPump'],'Plan gas separation first|Prepare water and power|Provide hydrogen and oxygen outlets|Start one section at a time|Observe stable operation'),
'q10':('oxygen',['Electrolyzer','GasPump','GasReservoir'],'Separate hydrogen and oxygen collection areas|Connect pumps and outlets|Start pumps separately|Inspect the exported gas|Keep maintenance access'),
'q13':('power',['GasReservoir','MethaneGenerator','LiquidReservoir'],'Buffer the natural gas|Connect the gas supply|Connect the generator|Provide polluted water and carbon dioxide outlets|Observe the fuel balance'),
'q16':('heat',['LiquidConditioner','LiquidReservoir','SteamTurbine'],'Design a closed loop|Check coolant phase change limits|Set a bypass and sensor|Choose a heat sink|Start sections separately'),
'q17':('heat',['OilRefinery','LiquidReservoir'],'Check recipes and byproducts|Connect crude oil|Provide product destinations|Isolate the hot area|Run a small batch'),
'q18':('heat',['MetalRefinery','SteamTurbine','LiquidConditioner'],'Prepare the steel ingredients|Prepare the coolant loop|Establish steam heat removal|Refine a small steel batch|Observe operation'),
'q19':('heat',['MetalRefinery','HydroponicFarm','LiquidConditioner'],'Measure temperature|Isolate production|Give plants separate temperature control|Check resource supplies|Integrate one section at a time'),
'q21':('room',['DiningTable','CookingStation','Bed'],'Inspect morale sources|Improve dining and schedules first|Arrange suitable food|Learn skills within the morale budget'),
'q23':('water',['OilWellCap','LiquidPump','LiquidReservoir'],'Locate an oil reservoir|Prepare a safe entrance|Connect water and power|Provide oil and gas outlets|Observe pressure release maintenance'),
'q24':('ranch',['RanchStation','ShearingStation','CreatureFeeder'],'Provide feed|Enclose the ranch|Set grooming and shearing|Assign a rancher|Observe growth and products'),
'q25':('buffer',['GasReservoir','GasPump','InsulationTile'],'Analyze activity and dormancy|Estimate average production|Prepare a buffer|Isolate temperature|Connect an outlet'),
'q26':('heat',['AutoMiner','SteamTurbine','SolidConduitInbox'],'Analyze the eruption|Isolate the hot area|Design heat removal|Set a collection route|Start only under controlled conditions'),
'q29':('food',['GourmetCookingStation','Refrigerator','GasReservoir'],'Read the recipe|Check sustainable ingredient output|Prepare fuel and a cook|Cook a small batch|Arrange food storage'),
'q33':('nature',['ParkSign','HydroponicFarm','FishFeeder'],'Read species requirements|Prepare suitable liquid or gas|Keep movement space|Plant or introduce the species|Observe survival'),
'q27':('rocket',['LaunchPad','CommandModule','SteamEngineCluster'],'Confirm the rocket route|Build the platform and required modules|Prepare fuel, oxygen and food|Check the departure list|Perform a short test flight'),
'q28':('rocket',['LaunchPad','CommandModule','ResearchModule'],'Select a destination|Check rocket modules|Prepare travel resources|Explore|Recover and use research data'),
'q30':('meteor',['BunkerDoor','BunkerTile','AutoMiner'],'Confirm the meteor risk|Choose the equipment to protect|Prepare protection and control|Check debris|Observe an actual event'),
'q31':('rocket',['LaunchPad','CommandModule','RationBox'],'Choose a destination|Check modules and range|Load survival supplies|Pack initial base materials|Rehearse a short trip'),
'q32':('settlement',['MineralDeoxidizer','Bed','Outhouse'],'Check the landing area|Prepare sanitation, sleep and oxygen|Arrange food and power|Prepare transport and a return route'),
'q34':('budget',['MineralDeoxidizer','RationBox','LiquidReservoir'],'Inspect oxygen, food and water|Check power and heat|Inspect essential consumables|Arrange backups and maintenance|Choose the next goal')
}
